### PR TITLE
feat: update template to include the running of microservice on cluster

### PR DESCRIPTION
**Pull request by clydevassallo**

### CODE REVIEW

**Review by ievgenii-shepeliuk — CHANGES_REQUESTED** [review]
`make test` should be run _before_ launching K3d, registry, and deploying helm chart.
for faster feedback.

**Comment by clydevassallo** [comment]
> `make test` should be run _before_ launching K3d, registry, and deploying helm chart. for faster feedback.

I actually moved this to the end intentionally because, so far, in averagely complex repos it is slower than all other steps combined: 
https://github.com/GiGInnovationLabs/endeavour-wallets/runs/4370483811?check_suite_focus=true

**Comment by ievgenii-shepeliuk** [comment]
> > `make test` should be run _before_ launching K3d, registry, and deploying helm chart. for faster feedback.
> 
> I actually moved this to the end intentionally to get faster feedback. So far, in averagely complex repos it is slower than all other steps combined: https://github.com/GiGInnovationLabs/endeavour-wallets/runs/4370483811?check_suite_focus=true

> > `make test` should be run _before_ launching K3d, registry, and deploying helm chart. for faster feedback.
> 
> I actually moved this to the end intentionally to get faster feedback. So far, in averagely complex repos it is slower than all other steps combined: https://github.com/GiGInnovationLabs/endeavour-wallets/runs/4370483811?check_suite_focus=true

Anyways, `make test` as it is now, must be called before try to attempt to build docker and deploy helm chart.

**Comment by clydevassallo** [comment]
> > > `make test` should be run _before_ launching K3d, registry, and deploying helm chart. for faster feedback.
> > 
> > 
> > I actually moved this to the end intentionally to get faster feedback. So far, in averagely complex repos it is slower than all other steps combined: https://github.com/GiGInnovationLabs/endeavour-wallets/runs/4370483811?check_suite_focus=true
> 
> > > `make test` should be run _before_ launching K3d, registry, and deploying helm chart. for faster feedback.
> > 
> > 
> > I actually moved this to the end intentionally to get faster feedback. So far, in averagely complex repos it is slower than all other steps combined: https://github.com/GiGInnovationLabs/endeavour-wallets/runs/4370483811?check_suite_focus=true
> 
> Anyways, `make test` as it is now, must be called before try to attempt to build docker and deploy helm chart.

As agreed, I've moved the make test before the build and deploy.
I've also moved the yaml files for external services and k3d to this repo

**Pull request merged**
